Housekeeping

diff --git a/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl b/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl
--- a/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl
+++ b/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl
@@ -20,13 +20,13 @@ alias rm='rm -i'
 
 # Detect which `ls` flavor is in use
 if ls --color >/dev/null 2>&1; then # GNU `ls`
-	colorflag="--color"
-	export CLICOLOR=1
-	export LS_COLORS='di=36:ln=1;31:so=37:pi=1;33:ex=35:bd=37:cd=37:su=37:sg=37:tw=32:ow=32:'
+  colorflag="--color"
+  export CLICOLOR=1
+  export LS_COLORS='di=36:ln=1;31:so=37:pi=1;33:ex=35:bd=37:cd=37:su=37:sg=37:tw=32:ow=32:'
 else # macOS `ls`
-	colorflag="-G"
-	export CLICOLOR=1
-	export LSCOLORS='gxBxhxDxfxhxhxhxhxcxcx'
+  colorflag="-G"
+  export CLICOLOR=1
+  export LSCOLORS='gxBxhxDxfxhxhxhxhxcxcx'
 fi
 
 # List all files colorized in long format
@@ -92,11 +92,11 @@ alias grbiur='git rebase --interactive --update-refs'
 alias groh='[[ ! -z $(git rev-parse --abbrev-ref --symbolic-full-name @{upstream}) ]] && git reset --hard $(git rev-parse --abbrev-ref --symbolic-full-name @{upstream})'
 
 function gco- {
-	if [[ $# == 1 ]]; then
-		git checkout @{-$1}
-	else
-		git checkout -
-	fi
+  if [[ $# == 1 ]]; then
+    git checkout @{-$1}
+  else
+    git checkout -
+  fi
 }
 
 {{ if eq .chezmoi.os "darwin" -}}
@@ -139,17 +139,17 @@ alias localip="networksetup -listallnetworkservices | grep -v '\*' | xargs -I{} 
 
 # Use bat in place of cat by default
 if [[ -x $(which bat) ]]; then
-	alias -g cat=bat
+  alias -g cat=bat
 fi
 
 # If ghead is installed, add an alias to trim new lines and copy to clipboard
 if [[ -x $(which ghead) ]]; then
-	alias cb="ghead -c -1 | pbcopy"
+  alias cb="ghead -c -1 | pbcopy"
 fi
 
 # If gfind is installed, add a default fancy find alias
 if [[ -x $(which gfind) ]]; then
-	alias f="gfind ! -path '*/.git/*' ! -path '*/vendor/*' ! -path '*/node_modules/*'"
+  alias f="gfind ! -path '*/.git/*' ! -path '*/vendor/*' ! -path '*/node_modules/*'"
 fi
 
 #######################################
@@ -157,192 +157,192 @@ fi
 #######################################
 
 function cleanupusb {
-	if [[ ! -z $(diskutil info $(pwd) | grep -E 'Device Location:\s+External') ]]; then
-		find . -name '._*' -delete
-		find . -name '.DS_Store' -delete
-		rm -rf .Spotlight-V100 .Trashes .fseventsd
-	else
-		echo "This command can only be run from an external drive"
-	fi
+  if [[ ! -z $(diskutil info $(pwd) | grep -E 'Device Location:\s+External') ]]; then
+    find . -name '._*' -delete
+    find . -name '.DS_Store' -delete
+    rm -rf .Spotlight-V100 .Trashes .fseventsd
+  else
+    echo "This command can only be run from an external drive"
+  fi
 }
 
 # Backup a file or folder
 function bak {
-	while (($#)); do
-		if [[ -r $1 && -w $(dirname $1) ]]; then
-			if [[ -d $1 ]]; then
-				cp -Rfp "$1" "$1.bak"
-			else
-				cp -i "$1" "$1.bak"
-			fi
-		fi
-		shift
-	done
+  while (($#)); do
+    if [[ -r $1 && -w $(dirname $1) ]]; then
+      if [[ -d $1 ]]; then
+        cp -Rfp "$1" "$1.bak"
+      else
+        cp -i "$1" "$1.bak"
+      fi
+    fi
+    shift
+  done
 }
 
 # Unbackup a file or folder
 function unbak {
-	while (($#)); do
-		if [[ -d "$1.bak" || -f "$1.bak" ]]; then
-			mv -f "$1.bak" "$1"
-		fi
-		shift
-	done
+  while (($#)); do
+    if [[ -d "$1.bak" || -f "$1.bak" ]]; then
+      mv -f "$1.bak" "$1"
+    fi
+    shift
+  done
 }
 
 # Backup a file of folder with date/time string in filename and exisiting extension
 function bakdate {
-	curDateTime=$(date +%Y%m%d-%H%M%S)
-	while (($#)); do
-		if [[ -d $1 ]]; then
-			cp -Rfp "$1" "$1-$curDateTime"
-		else
-			fullname=$(basename $1)
-			if [[ $fullname == *.* ]]; then
-				dirname=$(dirname $1)
-				filename="${fullname%%.*}"
-				extension="${fullname#*.}"
-				newName="$dirname/$filename-$curDateTime.$extension"
-			else
-				newName="$1-$curDateTime"
-			fi
-			cp -i "$1" "$newName"
-		fi
-		shift
-	done
+  curDateTime=$(date +%Y%m%d-%H%M%S)
+  while (($#)); do
+    if [[ -d $1 ]]; then
+      cp -Rfp "$1" "$1-$curDateTime"
+    else
+      fullname=$(basename $1)
+      if [[ $fullname == *.* ]]; then
+        dirname=$(dirname $1)
+        filename="${fullname%%.*}"
+        extension="${fullname#*.}"
+        newName="$dirname/$filename-$curDateTime.$extension"
+      else
+        newName="$1-$curDateTime"
+      fi
+      cp -i "$1" "$newName"
+    fi
+    shift
+  done
 }
 
 # Temporarily serve a directory
 function serveme {
-	portnum=8888
-	while [[ -n $(lsof -ti :$portnum) ]] && [[ $portnum -lt 9000 ]]; do
-		let portnum++
-	done
+  portnum=8888
+  while [[ -n $(lsof -ti :$portnum) ]] && [[ $portnum -lt 9000 ]]; do
+    let portnum++
+  done
 
-	if [[ $portnum -lt 9000 ]]; then
-		open "http://localhost:$portnum/"
-		php -d display_errors=0 -d log_errors=1 -d error_reporting=32767 -S localhost:$portnum
-	fi
+  if [[ $portnum -lt 9000 ]]; then
+    open "http://localhost:$portnum/"
+    php -d display_errors=0 -d log_errors=1 -d error_reporting=32767 -S localhost:$portnum
+  fi
 }
 
 # Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
 function targz {
-	local tmpFile="${@%/}.tar"
-	tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1
+  local tmpFile="${@%/}.tar"
+  tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1
 
-	size=$(
-		stat -f"%z" "${tmpFile}" 2>/dev/null # macOS `stat`
-		stat -c"%s" "${tmpFile}" 2>/dev/null # GNU `stat`
-	)
+  size=$(
+    stat -f"%z" "${tmpFile}" 2>/dev/null # macOS `stat`
+    stat -c"%s" "${tmpFile}" 2>/dev/null # GNU `stat`
+  )
 
-	local cmd=""
-	if ((size < 52428800)) && hash zopfli 2>/dev/null; then
-		# the .tar file is smaller than 50 MB and Zopfli is available; use it
-		cmd="zopfli"
-	else
-		if hash pigz 2>/dev/null; then
-			cmd="pigz"
-		else
-			cmd="gzip"
-		fi
-	fi
+  local cmd=""
+  if ((size < 52428800)) && hash zopfli 2>/dev/null; then
+    # the .tar file is smaller than 50 MB and Zopfli is available; use it
+    cmd="zopfli"
+  else
+    if hash pigz 2>/dev/null; then
+      cmd="pigz"
+    else
+      cmd="gzip"
+    fi
+  fi
 
-	echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`..."
-	"${cmd}" -v "${tmpFile}" || return 1
-	[ -f "${tmpFile}" ] && rm "${tmpFile}"
+  echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`..."
+  "${cmd}" -v "${tmpFile}" || return 1
+  [ -f "${tmpFile}" ] && rm "${tmpFile}"
 
-	zippedSize=$(
-		stat -f"%z" "${tmpFile}.gz" 2>/dev/null # macOS `stat`
-		stat -c"%s" "${tmpFile}.gz" 2>/dev/null # GNU `stat`
-	)
+  zippedSize=$(
+    stat -f"%z" "${tmpFile}.gz" 2>/dev/null # macOS `stat`
+    stat -c"%s" "${tmpFile}.gz" 2>/dev/null # GNU `stat`
+  )
 
-	echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully."
+  echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully."
 }
 
 # Determine size of a file or total size of a directory
 function fs {
-	if du -b /dev/null >/dev/null 2>&1; then
-		local arg=-sbh
-	else
-		local arg=-sh
-	fi
-	if [[ -n "$@" ]]; then
-		du $arg -- "$@"
-	else
-		du $arg .[^.]* ./*
-	fi
+  if du -b /dev/null >/dev/null 2>&1; then
+    local arg=-sbh
+  else
+    local arg=-sh
+  fi
+  if [[ -n "$@" ]]; then
+    du $arg -- "$@"
+  else
+    du $arg .[^.]* ./*
+  fi
 }
 
 # Create a data URL from a file
 function dataurl {
-	local mimeType=$(file -b --mime-type "$1")
-	if [[ $mimeType == text/* ]]; then
-		mimeType="${mimeType};charset=utf-8"
-	fi
-	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"
+  local mimeType=$(file -b --mime-type "$1")
+  if [[ $mimeType == text/* ]]; then
+    mimeType="${mimeType};charset=utf-8"
+  fi
+  echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"
 }
 
 # Run `dig * A` and display the most useful info
 function diga {
-	dig +nocmd -q "$1" -t A +multiline +noall +answer
+  dig +nocmd -q "$1" -t A +multiline +noall +answer
 }
 
 # Run `dig * any` and display the most useful info
 function digany {
-	dig +nocmd -q "$1" -t ANY +multiline +noall +answer
+  dig +nocmd -q "$1" -t ANY +multiline +noall +answer
 }
 
 # Normalize `open` across Linux, macOS, and Windows.
 # This is needed to make the `o` function (see below) cross-platform.
 if [ ! $(uname -s) = 'Darwin' ]; then
-	if grep -q Microsoft /proc/version; then
-		# Ubuntu on Windows using the Linux subsystem
-		alias open='explorer.exe'
-	else
-		alias open='xdg-open'
-	fi
+  if grep -q Microsoft /proc/version; then
+    # Ubuntu on Windows using the Linux subsystem
+    alias open='explorer.exe'
+  else
+    alias open='xdg-open'
+  fi
 fi
 
 function openWith {
-	if [[ $# > 0 ]]; then
-		case "$1" in
-		c)
-			opener='code'
-			shift
-			;;
-		v)
-			opener='vim'
-			shift
-			;;
-		o)
-			opener='open'
-			shift
-			;;
-		esac
-	fi
+  if [[ $# > 0 ]]; then
+    case "$1" in
+    c)
+      opener='code'
+      shift
+      ;;
+    v)
+      opener='vim'
+      shift
+      ;;
+    o)
+      opener='open'
+      shift
+      ;;
+    esac
+  fi
 
-	opener="${opener:-open}"
+  opener="${opener:-open}"
 
-	if [[ $# == 0 ]]; then
-		$opener .
-	else
-		$opener "$@"
-	fi
+  if [[ $# == 0 ]]; then
+    $opener .
+  else
+    $opener "$@"
+  fi
 }
 
 # `c` with no arguments opens the current directory in vscode, otherwise opens the given location
 function c {
-	openWith $0 "$@"
+  openWith $0 "$@"
 }
 
 # `v` with no arguments opens the current directory in Vim, otherwise opens the given location
 function v {
-	openWith $0 "$@"
+  openWith $0 "$@"
 }
 
 # `o` with no arguments opens the current directory, otherwise opens the given location
 function o {
-	openWith $0 "$@"
+  openWith $0 "$@"
 }
 
 # `treee` is a shorthand for `tree` with hidden files and color enabled, ignoring
@@ -350,73 +350,73 @@ function o {
 # `less` with options to preserve color and line numbers, unless the output is
 # small enough for one screen.
 function treee {
-	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX
+  tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX
 }
 
 # Enable TouchID for sudo in terminal
 function enable-touch-id-sudo {
-	case $(
-		grep -sqE "^[^#]+.*pam_tid\.so$" /etc/pam.d/sudo
-		echo $?
-	) in
-	0)
-		echo "TouchID unlock already in place"
-		;;
-	1)
-		sudo sed -i '' '1a\
+  case $(
+    grep -sqE "^[^#]+.*pam_tid\.so$" /etc/pam.d/sudo
+    echo $?
+  ) in
+  0)
+    echo "TouchID unlock already in place"
+    ;;
+  1)
+    sudo sed -i '' '1a\
 auth       sufficient     pam_tid.so
 ' /etc/pam.d/sudo && echo "TouchID unlock enabled" || echo "Error trying to write /etc/pam.d/sudo"
-		;;
-	*)
-		echo "Error trying to read /etc/pam.d/sudo"
-		;;
-	esac
+    ;;
+  *)
+    echo "Error trying to read /etc/pam.d/sudo"
+    ;;
+  esac
 }
 
 # Set screenshot location
 function set-screenshot-location {
-	if [[ -z "$1" ]]; then
-		echo "Usage: set-screenshot-location <path>"
-		return 1
-	fi
-	if [[ ! -d "$1" ]]; then
-		echo "Path $1 does not exist"
-		return 1
-	fi
-	defaults write com.apple.screencapture location "$1"
-	killall SystemUIServer
+  if [[ -z "$1" ]]; then
+    echo "Usage: set-screenshot-location <path>"
+    return 1
+  fi
+  if [[ ! -d "$1" ]]; then
+    echo "Path $1 does not exist"
+    return 1
+  fi
+  defaults write com.apple.screencapture location "$1"
+  killall SystemUIServer
 }
 {{ else -}}
 function openWith {
-	if [[ $# > 0 ]]; then
-		case "$1" in
-		c)
-			opener='code'
-			shift
-			;;
-		v)
-			opener='vim'
-			shift
-			;;
-		esac
-	fi
+  if [[ $# > 0 ]]; then
+    case "$1" in
+    c)
+      opener='code'
+      shift
+      ;;
+    v)
+      opener='vim'
+      shift
+      ;;
+    esac
+  fi
 
-	opener="${opener:-code}"
+  opener="${opener:-code}"
 
-	if [[ $# == 0 ]]; then
-		$opener .
-	else
-		$opener "$@"
-	fi
+  if [[ $# == 0 ]]; then
+    $opener .
+  else
+    $opener "$@"
+  fi
 }
 
 # `c` with no arguments opens the current directory in vscode, otherwise opens the given location
 function c {
-	openWith $0 "$@"
+  openWith $0 "$@"
 }
 
 # `v` with no arguments opens the current directory in Vim, otherwise opens the given location
 function v {
-	openWith $0 "$@"
+  openWith $0 "$@"
 }
 {{ end -}}
diff --git a/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl b/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl
--- a/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl
+++ b/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl
@@ -1,124 +1,125 @@
 # Shopify-specific aliases
 alias dcd='dev cd'
-alias osui='dev cd online-store-ui'
-alias osw='dev cd online-store-web'
-alias sfr='dev cd storefront-renderer'
+# alias osui='dev cd online-store-ui'
+# alias osw='dev cd online-store-web'
+# alias sfr='dev cd storefront-renderer'
 alias shp='dev cd shopify'
+alias core='dev cd shopify'
 alias web='dev cd admin-web'
-alias drup='dev reup'
-alias dref='dev reup && dev restart --all'
+alias drup='dev down && dev up'
+alias dref='dev down && dev up && dev restart --all'
 
 if [ "$SPIN" ]; then
-	dev config set suppress-info.notifications.up true
+  dev config set suppress-info.notifications.up true
 fi
 
 {{ if eq .chezmoi.os "darwin" -}}
 function current_repo {
-	local repo=$(git rev-parse --show-toplevel 2>/dev/null)
-	if [[ $? -ne 0 ]]; then
-		return 1
-	fi
-	echo $(basename $repo)
+  local repo=$(git rev-parse --show-toplevel 2>/dev/null)
+  if [[ $? -ne 0 ]]; then
+    return 1
+  fi
+  echo $(basename $repo)
 }
 
 beta_flags_path="$HOME/.DEFAULT_SPIN_BETA_FLAGS"
 
 if [[ -s $beta_flags_path && -r $beta_flags_path ]]; then
-	source $beta_flags_path
+  source $beta_flags_path
 else
-	export DEFAULT_SPIN_BETA_FLAGS=""
+  export DEFAULT_SPIN_BETA_FLAGS=""
 fi
 
 function sup {
-	local repo=""
-	local branch=""
-	local name=""
-	local flags=""
-	local input="$@"
-	local args=()
-	local raw_args=()
-	local name_length=48
+  local repo=""
+  local branch=""
+  local name=""
+  local flags=""
+  local input="$@"
+  local args=()
+  local raw_args=()
+  local name_length=48
 
-	while (($#)); do
-		local params=$#
-		case "$1" in
-		-b=* | --branch=*)
-			if [[ -z $branch ]]; then
-				branch=${1/--branch=/-b=}
-				branch=${branch/#-b=/}
-				shift
-			fi
-			;;
-		-n=* | --name=*)
-			if [[ -z $name ]]; then
-				name=${1/--name=/-n=}
-				name=${name/#-n=/}
-				shift
-			fi
-			;;
-		-r=* | --repo=*)
-			if [[ -z $repo ]]; then
-				repo=${1/--repo=/-r=}
-				repo=${repo/#-r=/}
-				shift
-			fi
-			;;
-		-f=* | --flags=*)
-			if [[ -z $flags ]]; then
-				flags=${1/--flags=/-f=}
-				flags=${flags/#-f=/}
-				shift
-			fi
-			;;
-		--)
-			shift
-			raw_args=("$@")
-			while (($#)); do
-				shift
-			done
-			;;
-		*)
-			if [[ -z $name && ! $1 = -* ]]; then
-				name=${1/--name=/-n=}
-				name=${name/#-n=/}
-				shift
-			fi
-			;;
-		esac
+  while (($#)); do
+    local params=$#
+    case "$1" in
+    -b=* | --branch=*)
+      if [[ -z $branch ]]; then
+        branch=${1/--branch=/-b=}
+        branch=${branch/#-b=/}
+        shift
+      fi
+      ;;
+    -n=* | --name=*)
+      if [[ -z $name ]]; then
+        name=${1/--name=/-n=}
+        name=${name/#-n=/}
+        shift
+      fi
+      ;;
+    -r=* | --repo=*)
+      if [[ -z $repo ]]; then
+        repo=${1/--repo=/-r=}
+        repo=${repo/#-r=/}
+        shift
+      fi
+      ;;
+    -f=* | --flags=*)
+      if [[ -z $flags ]]; then
+        flags=${1/--flags=/-f=}
+        flags=${flags/#-f=/}
+        shift
+      fi
+      ;;
+    --)
+      shift
+      raw_args=("$@")
+      while (($#)); do
+        shift
+      done
+      ;;
+    *)
+      if [[ -z $name && ! $1 = -* ]]; then
+        name=${1/--name=/-n=}
+        name=${name/#-n=/}
+        shift
+      fi
+      ;;
+    esac
 
-		if [[ $# == $params ]]; then
-			echo "Incorrect arguments provided ($# leftover): \"$@\""
-			return 1
-		fi
-	done
+    if [[ $# == $params ]]; then
+      echo "Incorrect arguments provided ($# leftover): \"$@\""
+      return 1
+    fi
+  done
 
-	[[ -z $repo ]] && repo=$(current_repo)
+  [[ -z $repo ]] && repo=$(current_repo)
 
-	if [[ -z $repo ]]; then
-		echo "Missing required argument: --repo"
-		return 1
-	fi
+  if [[ -z $repo ]]; then
+    echo "Missing required argument: --repo"
+    return 1
+  fi
 
-	if [[ -z $flags ]]; then
-		flags=$DEFAULT_SPIN_BETA_FLAGS
-	fi
+  if [[ -z $flags ]]; then
+    flags=$DEFAULT_SPIN_BETA_FLAGS
+  fi
 
-	if [[ -z $name ]]; then
-		name=${branch/#[a-zA-Z0-9]*\//}
-		if [[ ${#name} > $name_length ]]; then
-			name=${name:0:$name_length}
-		fi
-	fi
+  if [[ -z $name ]]; then
+    name=${branch/#[a-zA-Z0-9]*\//}
+    if [[ ${#name} > $name_length ]]; then
+      name=${name:0:$name_length}
+    fi
+  fi
 
-	if [[ ! -z $branch ]]; then
-		repo="$repo@$branch"
-	fi
-	if [[ ! -z $name ]]; then
-		args=("${args[@]}" "--name" "${name//[^a-zA-Z0-9-]/-}")
-	fi
+  if [[ ! -z $branch ]]; then
+    repo="$repo@$branch"
+  fi
+  if [[ ! -z $name ]]; then
+    args=("${args[@]}" "--name" "${name//[^a-zA-Z0-9-]/-}")
+  fi
 
-	echo spin up --config shopify.env.SHOP_1_BETA_FLAGS="$flags" $repo --wait "${args[@]}" "${raw_args[@]}"
-	spin up --config shopify.env.SHOP_1_BETA_FLAGS="$flags" $repo --wait "${args[@]}" "${raw_args[@]}"
+  echo spin up --config shopify.env.SHOP_1_BETA_FLAGS="$flags" $repo --wait "${args[@]}" "${raw_args[@]}"
+  spin up --config shopify.env.SHOP_1_BETA_FLAGS="$flags" $repo --wait "${args[@]}" "${raw_args[@]}"
 }
 
 alias suposw='sup --repo=online-store-web'
@@ -126,8 +127,8 @@ alias supweb='sup --repo=web'
 alias supmedia='sup --repo=shopify:media'
 {{ else -}}
 if [[ $TERM_PROGRAM == vscode ]]; then
-	export GIT_EDITOR="code -w"
+  export GIT_EDITOR="code -w"
 else
-	export GIT_EDITOR="vim"
+  export GIT_EDITOR="vim"
 fi
 {{ end -}}
