Add function to enable TouchId for sudo

diff --git a/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl b/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl
--- a/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl
+++ b/dot_oh-my-zsh/custom/30-aliases.zsh.tmpl
@@ -337,6 +337,23 @@ function o {
 function treee {
   tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;
 }
+
+# Enable TouchID for sudo in terminal
+function enable-touch-id-sudo {
+  case `grep -sqE "^[^#]+.*pam_tid\.so$" /etc/pam.d/sudo; echo $?` in
+  0)
+    echo "TouchID unlock already in place"
+    ;;
+  1)
+    sudo sed -i '' '1a\
+auth       sufficient     pam_tid.so
+' /etc/pam.d/sudo && echo "TouchID unlock enabled" || echo "Error trying to write /etc/pam.d/sudo"
+    ;;
+  *)
+    echo "Error trying to read /etc/pam.d/sudo"
+    ;;
+esac
+}
 {{ else -}}
 function openWith {
   if [[ $# > 0 ]]; then
