Autoformat

diff --git a/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl b/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl
--- a/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl
+++ b/dot_oh-my-zsh/custom/50-shopify.zsh.tmpl
@@ -14,93 +14,93 @@ fi
 
 {{ if eq .chezmoi.os "darwin" -}}
 function current_repo {
-  local repo=$(git rev-parse --show-toplevel 2> /dev/null)
-  if [[ $? -ne 0 ]]; then
-    return 1
-  fi
-  echo `basename $repo`
+	local repo=$(git rev-parse --show-toplevel 2>/dev/null)
+	if [[ $? -ne 0 ]]; then
+		return 1
+	fi
+	echo $(basename $repo)
 }
 
-beta_flags_path="$HOME/.DEFAULT_SPIN_BETA_FLAGS";
+beta_flags_path="$HOME/.DEFAULT_SPIN_BETA_FLAGS"
 
 if [[ -s $beta_flags_path && -r $beta_flags_path ]]; then
-  source $beta_flags_path;
+	source $beta_flags_path
 else
-  export DEFAULT_SPIN_BETA_FLAGS=""
+	export DEFAULT_SPIN_BETA_FLAGS=""
 fi
 
 function sup {
-  local repo=""
-  local branch=""
-  local name=""
-  local input="$@"
-  local args=()
-  local raw_args=()
+	local repo=""
+	local branch=""
+	local name=""
+	local input="$@"
+	local args=()
+	local raw_args=()
 
-  while (($#)); do
-    local params=$#
-    case "$1" in
-    -b=* | --branch=*)
-      if [[ -z $branch ]]; then
-        branch=${1/--branch=/-b=}
-        branch=${branch/#-b=/}
-        shift
-      fi
-      ;;
-    -n=* | --name=*)
-      if [[ -z $name ]]; then
-        name=${1/--name=/-n=}
-        name=${name/#-n=/}
-        shift
-      fi
-      ;;
-    -r=* | --repo=*)
-      if [[ -z $repo ]]; then
-        repo=${1/--repo=/-r=}
-        repo=${repo/#-r=/}
-        shift
-      fi
-      ;;
-    --)
-      shift
-      raw_args=("$@")
-      while (($#)); do
-        shift
-      done
-      ;;
-    *)
-      if [[ -z $name && ! $1 = -* ]]; then
-        name=${1/--name=/-n=}
-        name=${name/#-n=/}
-        shift
-      fi
-      ;;
-    esac
+	while (($#)); do
+		local params=$#
+		case "$1" in
+		-b=* | --branch=*)
+			if [[ -z $branch ]]; then
+				branch=${1/--branch=/-b=}
+				branch=${branch/#-b=/}
+				shift
+			fi
+			;;
+		-n=* | --name=*)
+			if [[ -z $name ]]; then
+				name=${1/--name=/-n=}
+				name=${name/#-n=/}
+				shift
+			fi
+			;;
+		-r=* | --repo=*)
+			if [[ -z $repo ]]; then
+				repo=${1/--repo=/-r=}
+				repo=${repo/#-r=/}
+				shift
+			fi
+			;;
+		--)
+			shift
+			raw_args=("$@")
+			while (($#)); do
+				shift
+			done
+			;;
+		*)
+			if [[ -z $name && ! $1 = -* ]]; then
+				name=${1/--name=/-n=}
+				name=${name/#-n=/}
+				shift
+			fi
+			;;
+		esac
 
-    if [[ $# == $params ]]; then
-      echo "Incorrect arguments provided: \"$input\""
-      return 1
-    fi
-  done
+		if [[ $# == $params ]]; then
+			echo "Incorrect arguments provided: \"$input\""
+			return 1
+		fi
+	done
 
-  [[ -z $repo ]] && repo=`current_repo`
+	[[ -z $repo ]] && repo=$(current_repo)
 
-  if [[ -z $repo ]]; then
-    echo "Missing required argument: --repo"
-    return 1
-  fi
+	if [[ -z $repo ]]; then
+		echo "Missing required argument: --repo"
+		return 1
+	fi
 
-  [[ -z $name ]] && name=${branch/#jtwee\//}
+	[[ -z $name ]] && name=${branch/#jtwee\//}
 
-  if [[ ! -z $branch ]]; then
-    repo="$repo@$branch"
-  fi
-  if [[ ! -z $name ]]; then
-    args=("${args[@]}" "--name" "${name//[^a-z0-9-]/-}")
-  fi
+	if [[ ! -z $branch ]]; then
+		repo="$repo@$branch"
+	fi
+	if [[ ! -z $name ]]; then
+		args=("${args[@]}" "--name" "${name//[^a-z0-9-]/-}")
+	fi
 
-  echo spin up --config shopify.env.SHOP_1_BETA_FLAGS="${DEFAULT_SPIN_BETA_FLAGS}" $repo --wait "${args[@]}" "${raw_args[@]}"
-  spin up --config shopify.env.SHOP_1_BETA_FLAGS="${DEFAULT_SPIN_BETA_FLAGS}" $repo --wait "${args[@]}" "${raw_args[@]}"
+	echo spin up --config shopify.env.SHOP_1_BETA_FLAGS="${DEFAULT_SPIN_BETA_FLAGS}" $repo --wait "${args[@]}" "${raw_args[@]}"
+	spin up --config shopify.env.SHOP_1_BETA_FLAGS="${DEFAULT_SPIN_BETA_FLAGS}" $repo --wait "${args[@]}" "${raw_args[@]}"
 }
 
 alias suposw='sup --repo=online-store-web'
@@ -108,8 +108,8 @@ alias supweb='sup --repo=web:minimal'
 alias supmedia='sup --repo=shopify:media'
 {{ else -}}
 if [[ $TERM_PROGRAM == vscode ]]; then
-  export GIT_EDITOR="code -w"
+	export GIT_EDITOR="code -w"
 else
-  export GIT_EDITOR="vim"
+	export GIT_EDITOR="vim"
 fi
 {{ end -}}
